name: silent_moon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-243.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  vector_graphics: ^1.1.19

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  vector_graphics_compiler: ^1.1.17

flutter:
  uses-material-design: true
  assets:
    - "assets/a/"
    - "assets/logos/"
    - "assets/topics/"
    - "assets/icons/"
    - "assets/logo.svg"
